CREATE DATABASE DB_CAMMY_RH;
USE DB_CAMMY_RH;
-- ATIVIDADE SOBRE CRIAR UM BANCO DE DADOS PARA UM RH --
CREATE TABLE TB_FUNCIONARIOS(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR (1000),
DEPARTAMENTO CHAR (255),
FUCAO VARCHAR (255),
IDADE INT,
SALARIO NUMERIC (5,2),
PRIMARY KEY (ID));

SELECT * FROM TB_FUNCIONARIOS;
INSERT INTO TB_FUNCIONARIOS(NOME,DEPARTAMENTO,FUNCAO,IDADE,SALARIO)
VALUES("ITACHI","ADMINISTRATIVO","AUXILIAR",28,1200,35),
	   ("DEIDARA","GERENCIA","GERENTE",50,8750,68);
       

SELECT * FROM TB_FUNCIONARIOS WHERE SALARIO >= 2000;
SELECT * FROM TB_FUNCIONARIOS WHERE SALARIO < 2000;
UPDATE TB_FUNCIONARIOS SET SALARIO = 1500 WHERE ID = 1;