CREATE DATABASE DB_ESCOLA;
USE DB_ESCOLA;

CREATE TABLE DADOS_ALUNOS(
ID INT AUTO_INCREMENT,
NOME VARCHAR (30),
IDADE INT,
SERIE VARCHAR (20),
NOTA FLOAT,
PRIMARY KEY (ID));

SELECT * FROM DADOS_ALUNOS;
INSERT INTO DADOS_ALUNOS (NOME, IDADE, SERIE, NOTA)
VALUES ("EDWARD", 16, "3A", 9.5),
	   ("ALPHONSE", 13, "8C", 9.8),
       ("WINRY", 15, "2B", 7.0);
       
SELECT * FROM DADOS_ALUNOS WHERE NOTA > 7;
SELECT * FROM DADOS_ALUNOS WHERE NOTA < 7;
UPDATE DADOS_ALUNOS SET NOVA = 10 WHERE ID;
       