CREATE DATABASE DB_LOJA_VIRTUAL;
USE DB_LOJA_VIRTUAL;
-- ATIVIDADE DE CRIAR UM BANCO DE DADOS COM 8 REGISTROS DE UMA LOJA VIRTUAL--
CREATE TABLE TB_PRODUTOS(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR (1000),
QUANTIDADE INT,
PRECO NUMERIC(9,2),
DESCRICAO CHAR (255),
PRIMARY KEY (ID));

SELECT * FROM TB_PRODUTOS;
INSERT INTO TB_PRODUTOS (NOME, QUANTIDADE, PRECO, DESCRICAO)
VALUES ("COTURNO", 29, 579.50, "MARCA REVERSA DA COR PRETA"),
       ("CORSET", 57, 55.58, "COR VERMELHA PRODUTO IMPORTADO"),
       ("SOBRETUDO", 75, 578.52, "COR ROXA DA MARCA SWEET SAM"),
       ("CALÇA", 54, 45.56, "CALÇA DE VINIL"),
       ("SAIA", 06, 32.65, "SAIA RODADA DA COR VERMELHA"),
       ("MOLETOM", 47, 54.78, "MOLETOM COM ESTAMPA DO ANIME EVANGELION"),
       ("CAMISETA", 68, 62.98, "CAMISETA COM ESTAMPA DO DRACULA"),
       ("BIQUINI", 39, 26.51, "BIQUINI COM ESTAMPA DE MORCEGO");

-- MAIOR  VALOR --
SELECT * FROM TB_PRODUTOS WHERE PRECO > 500.00;

-- MENOR VALOR --
SELECT * FROM TB_PRODUTOS WHERE PRECO < 500.00;

-- ATUALIZANDO UM VALOR -- 
UPDATE TB_PRODUTOS SET PRECO = 501.00 WHERE ID = 2;

       
       
       
       


