CREATE DATABASE DB_CURSO_DA_MINHA_VIDA;
USE DB_CURSO_DA_MINHA_VIDA;

CREATE TABLE TB_CATEGORIAS(
ID BIGINT AUTO_INCREMENT,
AREA VARCHAR (255) NOT NULL,
PRIMARY KEY (ID));

CREATE TABLE TB_CURSOS(
CODIGO BIGINT AUTO_INCREMENT,
NOME VARCHAR (255) NOT NULL,
MODALIDADE VARCHAR (255),
PRECO FLOAT (6,2),
CATEGORIA_ID BIGINT,
PRIMARY KEY (CODIGO),
FOREIGN KEY (CATEGORIA_ID) REFERENCES TB_CATEGORIAS (ID));

INSERT INTO TB_CATGORIAS (AREA)
VALUES ("ÁREA DE SAÚDE");
INSERT INTO TB_CATGORIAS (AREA)
VALUES ("IDIOMAS");
INSERT INTO TB_CATGORIAS (AREA)
VALUES ("HUMANAS");
INSERT INTO TB_CATGORIAS (AREA)
VALUES ("CULINÁRIA");
INSERT INTO TB_CATGORIAS (AREA)
VALUES ("TECNOLOGIA");

SELECT * FROM TB_CATEGORIAS;

INSERT INTO TB_CURSOS (NOME, MODALIDADE, PRECO, CATEGORIA_ID)
VALUES ("CIÊNCIAS MORTUÁRIAS", "PRESENCIAL", 1200, 1);
INSERT INTO TB_CURSOS (NOME, MODALIDADE, PRECO, CATEGORIA_ID)
VALUES ("ESPANHOL", "ONLINE", 800, 2);
INSERT INTO TB_CURSOS (NOME, MODALIDADE, PRECO, CATEGORIA_ID)
VALUES ("CURSO DE DUBLAGEM", "HIBRIDO", 1500, 3);
INSERT INTO TB_CURSOS (NOME, MODALIDADE, PRECO, CATEGORIA_ID)
VALUES ("CURSO DE CONFEITARIA BÁSICA", "PRESENCIAL", 500, 4);
INSERT INTO TB_CURSOS (NOME, MODALIDADE, PRECO, CATEGORIA_ID)
VALUES ("CURSO DE FRONT END AVANÇADO", "ONLINE", 250, 5);
INSERT INTO TB_CURSOS (NOME, MODALIDADE, PRECO, CATEGORIA_ID)
VALUES ("CURSO DE AUXILIAR DE NECRÓPSIA", "PRESENCIAL", 2500, 1);
INSERT INTO TB_CURSOS (NOME, MODALIDADE, PRECO, CATEGORIA_ID)
VALUES ("JAPONES", "ONLINE", 950, 2);
INSERT INTO TB_CURSOS (NOME, MODALIDADE, PRECO, CATEGORIA_ID)
VALUES ("CURSO DE TEATRO", "PRESENCIAL", 3500, 3);

SELECT * FROM TB_CURSOS;

SELECT * FROM TB_CURSOS WHERE PRECO > 500;
SELECT * FROM TB_CURSOS WHERE PRECO >= 600 AND PRECO <= 1000;
SELECT * FROM TB_CURSOS WHERE NOME LIKE "%J%";
SELECT * FROM TB_CURSOS INNER JOIN TB_CATEGORIAS ON TB_CURSOS.CATEGORIA_ID = TB_CATEGORIAS.ID;
SELECT * FROM TB_CURSOS INNER JOIN TB_CATEGORIAS ON TB_CURSOS.CATEGORIA_ID = TB_CATEGORIAS.ID WHERE ID = 3;