CREATE DATABASE DB_FARMACIA_BEM_ESTAR;
USE DB_FARMACIA_BEM_ESTAR;

CREATE TABLE TB_CATEGORIAS(
ID BIGINT AUTO_INCREMENT,
DESCRICAO VARCHAR (255) NOT NULL,
PRIMARY KEY (ID));

CREATE TABLE TB_PRODUTOS(
REFERENCIA BIGINT AUTO_INCREMENT,
NOME VARCHAR (255) NOT NULL,
PRECO FLOAT (6,2) NOT NULL,
CATEGORIA_ID BIGINT,
PRIMARY KEY (REFERENCIA),
FOREIGN KEY (CATEGORIA_ID) REFERENCES TB_CATEGORIAS (ID));

INSERT INTO TB_CATEGORIAS (DESCRICAO)
VALUES ("MEDICAMENTOS");
INSERT INTO TB_CATEGORIAS (DESCRICAO)
VALUES ("BELEZA");
INSERT INTO TB_CATEGORIAS (DESCRICAO)
VALUES ("HIGIENE");
INSERT INTO TB_CATEGORIAS (DESCRICAO)
VALUES ("DERMOCOSMÉTICOS");
INSERT INTO TB_CATEGORIAS (DESCRICAO)
VALUES ("INFANTIL");

SELECT * FROM TB_CATEGORIAS;

INSERT INTO TB_PRODUTOS (NOME, PRECO, CATEGORIA_ID)
VALUES ("NEOSORO", 5.00, 1);
INSERT INTO TB_PRODUTOS (NOME, PRECO, CATEGORIA_ID)
VALUES ("REMOVEDOR DE ESMALTE A BASE DE ACETONA", 4.45, 2);
INSERT INTO TB_PRODUTOS (NOME, PRECO, CATEGORIA_ID)
VALUES ("SABONETE EM BARRA DOVE", 3.90, 3);
INSERT INTO TB_PRODUTOS (NOME, PRECO, CATEGORIA_ID)
VALUES ("SHAMPOO ANTICASPA VICHY", 65.90, 4);
INSERT INTO TB_PRODUTOS (NOME, PRECO, CATEGORIA_ID)
VALUES ("NINHO NUTRIGOLD", 36.90, 5);
INSERT INTO TB_PRODUTOS (NOME, PRECO, CATEGORIA_ID)
VALUES ("CIMEGRIPE", 9.90, 1);
INSERT INTO TB_PRODUTOS (NOME, PRECO, CATEGORIA_ID)
VALUES ("ÁGUA OXIGENADA FARMAX", 3.75, 2);
INSERT INTO TB_PRODUTOS (NOME, PRECO, CATEGORIA_ID)
VALUES ("PRESERVATIVO PRUDENCE", 11.90, 3);

SELECT * FROM TB_PRODUTOS;

SELECT * FROM TB_PRODUTOS WHERE PRECO > 50;
SELECT * FROM TB_PRODUTOS WHERE PRECO >= 5 AND PRECO <= 60;
SELECT * FROM TB_PRODUTOS WHERE NOME LIKE "%C%";
SELECT * FROM TB_PRODUTOS INNER JOIN TB_CATEGORIAS ON TB_PRODUTOS.CATEGORIA_ID = TB_CATEGORIAS.ID;
SELECT * FROM TB_PRODUTOS INNER JOIN TB_CATEGORIAS ON TB_PRODUTOS.CATEGORIA_ID = TB_CATEGORIAS.ID WHERE ID = 1;

