CREATE DATABASE DB_PIZZARIA_LEGAL;
USE DB_PIZZARIA_LEGAL;

CREATE TABLE TB_CATEGORIAS (
ID BIGINT (5) AUTO_INCREMENT,
TAMANHO VARCHAR (255) NOT NULL,
PRECO FLOAT (6,2) NOT NULL,
PRIMARY KEY (ID));

CREATE TABLE TB_PIZZAS (
ID BIGINT (5) AUTO_INCREMENT,
SABOR VARCHAR (255) NOT NULL,
INGREDIENTES VARCHAR (255),
DESCRICAO VARCHAR (255),
CATEGORIA_ID BIGINT,
PRIMARY KEY (ID),
FOREIGN KEY (CATEGORIA_ID) 
REFERENCES TB_CATEGORIAS (ID));

INSERT INTO TB_CATEGORIAS (TAMANHO, PRECO)
VALUES ("GIGANTE", 90.50);
INSERT INTO TB_CATEGORIAS (TAMANHO, PRECO)
VALUES ("GRANDE", 70.70);
INSERT INTO TB_CATEGORIAS (TAMANHO, PRECO)
VALUES ("MÉDIA", 50.85);
INSERT INTO TB_CATEGORIAS (TAMANHO, PRECO)
VALUES ("PEQUENA", 30.75);
INSERT INTO TB_CATEGORIAS (TAMANHO, PRECO)
VALUES ("BROTINHO", 10.90);

SELECT * FROM TB_CATEGORIAS;

INSERT INTO TB_PIZZAS (SABOR, INGREDIENTES, DESCRICAO, CATEGORIA_ID)
VALUES ("ALHO E ÓLEO", "MUSSARELA, ALHO, TOMATE CEREJA E AZEITE DE OLIVA", "PIZZA TRADICIONAL", 1);
INSERT INTO TB_PIZZAS (SABOR, INGREDIENTES, DESCRICAO, CATEGORIA_ID)
VALUES ("ALEMÃ", "MUSSARELA, TOMATE E ALICCE", "PIZZA ESPECIAL", 2);
INSERT INTO TB_PIZZAS (SABOR, INGREDIENTES, DESCRICAO, CATEGORIA_ID)
VALUES ("MAÇARICO", "LINGUIÇA ESPECIAL DEFUMADA, PIMENTA CALABRESA, CEBOLA E ORÉGANO", "PIZZA PREDILETA", 3);
INSERT INTO TB_PIZZAS (SABOR, INGREDIENTES, DESCRICAO, CATEGORIA_ID)
VALUES ("FUNGHI", "MUSSARELA, FUNGHI ESPECIAL E QUEIJO TIPO CATUPIRY", "PIZZA PREMIUM", 4);
INSERT INTO TB_PIZZAS (SABOR, INGREDIENTES, DESCRICAO, CATEGORIA_ID)
VALUES ("BANANA", "POUCA MUSSARELA, BANANA E FAROFA ESPECIAL", "PIZZA DOCE TRADICIONAL", 5);
INSERT INTO TB_PIZZAS (SABOR, INGREDIENTES, DESCRICAO, CATEGORIA_ID)
VALUES ("BEIJINHO", "POUCA MUSSARELA, CHOCOLATE BRANCO, COCÔ RALADO E LEITE CONDENSADO", "PIZZA DOCE ESPECIAL", 6);
INSERT INTO TB_PIZZAS (SABOR, INGREDIENTES, DESCRICAO, CATEGORIA_ID)
VALUES ("LOMBO", "MUSSARELA E LOMBO", "PIZZA TRADICIONAL", 7);
INSERT INTO TB_PIZZAS (SABOR, INGREDIENTES, DESCRICAO, CATEGORIA_ID)
VALUES ("AMERICANA", "MUSSARELA, BACON EM CUBOS, OVO E CEBOLA", "PIZZA ESPECIAL", 8);

SELECT * FROM TB_PIZZAS;

SELECT * FROM TB_PIZZAS INNER JOIN TB_CATEGORIAS WHERE PRECO > 45;
SELECT * FROM TB_PIZZAS INNER JOIN TB_CATEGORIAS WHERE PRECO >= 50 AND PRECO <= 100;
SELECT * FROM TB_PIZZAS WHERE SABOR LIKE "%M%";
SELECT * FROM TB_PIZZAS INNER JOIN TB_CATEGORIAS ON TB_PIZZAS.CATEGORIA_ID = TB_CATEGORIAS.ID;
SELECT * FROM TB_PIZZAS INNER JOIN TB_CATEGORIAS ON TB_PIZZAS.CATEGORIA_ID = TB_CATEGORIAS.ID
WHERE CATEGORIA_ID = 3;




